version: '3'
services:
#  db:
#    image: postgres
#    volumes:
#      - ./tmp/db:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: myapp
#      POSTGRES_PASSWORD: secret
  web:
    build: .
    ports:
      - "3000:3000"
#    depends_on:
#      - db

